global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#nataly_naumenko'
