---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: reddit
    component: post-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post
      component: post-deployment
  template:
    metadata:
      name: post
      labels:
        app: post
        component: post-deployment
    spec:
      containers:
      - image: natali1701/post
        name: post
        env:
        - name: COMMENT_DATABASE_HOST
          value: post-db

